
build site:
  image: jekyll/jekyll:pages
  stage: build
  script:
    - bundle install --path=vendor
    - bundle exec jekyll build
    - mv _site xmppdk
  artifacts:
    expire_in: 1 month
    paths:
      - xmppdk

test site:
  image: mesosphere/linkchecker
  stage: test
  script:
  - apt-get update && apt-get install busybox
  - cd xmppdk
  - busybox httpd -p 4000
  - linkchecker http://localhost:4000/
