# Site settings
title: XMPP.DK jabber server
email: jesper@graffen.dk
description: > # this means to ignore newlines until "baseurl:"
  xmpp.dk is a secure, free and public XMPP/Jabber server that allows registration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xmpp.dk" # the base hostname & protocol for your site
twitter_username: xmppdk

fingerprints:
  otr: 6A99F136 E66972B9 B169D5B3 458828D1 4003240F
  tls:
    sha-256: 09 06 51 3A 63 DE 83 F6 C9 C7 97 06 6C A7 05 DA 79 8E 23 5E AE E9 3C FC 17 0E 53 97 91 A4 D5 E9
    sha-1: 22 D7 B2 6F 3F 40 3E B8 0B B6 67 E8 DA 09 2E 76 6C AD CB 47
    expiry: 2017-10-24

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']
