# Site settings
title: XMPP.DK jabber server
email: jesper@graffen.dk
description: > # this means to ignore newlines until "baseurl:"
  xmpp.dk is a secure, free and public XMPP/Jabber server that allows registration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xmpp.dk" # the base hostname & protocol for your site
twitter_username: xmppdk

fingerprints:
  otr: 6A99F136 E66972B9 B169D5B3 458828D1 4003240F
  tls:
    sha-256: 35 05 BD 0B 8E E5 91 2E 81 9E D7 89 8B 57 50 D2 C6 14 F8 3B 78 25 6D ED 1E A6 5B AC 01 8B FE 62
    sha-1: 2D 70 34 C4 BA 79 FC 6C 05 A8 E5 89 19 AB B8 29 E0 56 26 57
    expiry: 2017-07-27

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']

