# Site settings
title: XMPP.DK jabber server
email: jesper@graffen.dk
description: > # this means to ignore newlines until "baseurl:"
  xmpp.dk is a secure, free and public XMPP/Jabber server that allows registration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xmpp.dk" # the base hostname & protocol for your site
twitter_username: xmppdk

fingerprints:
  otr: 6A99F136 E66972B9 B169D5B3 458828D1 4003240F
  tls:
    sha-256: BE E3 86 67 3F B1 CC 16 50 4F 18 3A CF 9C B0 31 05 DC 05 41 E1 7E AD B1 BA 29 AF 5C 28 5F DE 1C
    sha-1: 3F 88 05 4D EE 8F B1 BD 0E 90 2C 3F 21 D8 13 6A 7C B6 74 EE
    expiry: 2017-05-28

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']

